name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Ninja
        if: matrix.os == 'ubuntu-latest'
        run: 'sudo apt-get install ninja-build freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev'
      - name: Build
        run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_INSTALL_PREFIX="install" -B build .
          cmake --build build --target install
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: install
