name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Ninja
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        run: 'sudo apt-get install ninja-build freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev'
      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_INSTALL_PREFIX="install" -B build .
          cmake --build build --target install
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: install/bin/GlslTest*
